---
title: "Bayesian ML"
author: "Ella Chee"
date: "2026-02-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bayesian Model for Wildfire Detection

## Get data from Kaggle
```{r, echo=TRUE}
install.packages("remotes")
library(kaggler)

# Authenticate creds
kgl_auth(username = "ellachee21", key = "KGAT_107e527829b7a3f5505e98b50142d7db")

# Download a dataset
system("/Users/nutellachee/anaconda3/bin/kaggle datasets download -d abdelghaniaaba/wildfire-prediction-dataset --unzip -p ./data")
```


## Load data

```{r}
# Helper to load both classes (no wildfire/wildfire) for given folder
load_data <- function(folder_name) {
  
  # Load list of images (no wildfire)
  nowildfire <- paste0(folder_name, "/nowildfire/")
  nowildfire_list <- map(nowildfire, 
                 function(x) paste0(x, list.files(x))
                 ) %>% 
  unlist()
  
  # Load list of images (no wildfire)
  wildfire <- paste0(folder_name, "/wildfire/")
  wildfire_list <- map(wildfire, 
                 function(x) paste0(x, list.files(x))
                 ) %>% 
  unlist()
  
  print(sprintf("%d images in no wildfire class", length(nowildfire_list)))
  print(sprintf("%d images in wildfire class", length(wildfire_list)))
  
  return(list(nowildfire_list, wildfire_list))
  
}

```

Load validation, training, testing sets

```{r}
# Load validation data
print("VALIDATION:")
valid_results <- load_data("data/valid")
valid_nowildfire <- valid_results[[1]]
valid_wildfire <- valid_results[[2]]

# Load training data
print("TRAINING:")
train_results <- load_data("data/train")
train_nowildfire <- train_results[[1]]
train_wildfire <- train_results[[2]]

# Load testing data
print("TESTING:")
test_results <- load_data("data/test")
test_nowildfire <- test_results[[1]]
test_wildfire <- test_results[[2]]


```

## Preview image data

```{r, echo=TRUE}
# Randomly select image
set.seed(99)
random_img <- sample(test_wildfire, 1)

# Load image into R
img <- image_read(random_img)
print(img)

# Load image as array of values
img_array <- as.numeric(image_data(img, channels = "rgb"))
dim(img_array)

```

